name: "yolov5"
platform: "tensorrt_plan"
max_batch_size: 4
input: [
    {
        name: "data"
        data_type: TYPE_FP32
        format: FORMAT_NONE
        dims: [ 3, 640, 640 ]
    }
]
output: [
    {
        name: "prob",
        data_type: TYPE_FP32
        dims: [ 6001, 1, 1 ]
    }
]

dynamic_batching {
	preferred_batch_size: [ 2, 4 ]
}

instance_group: [
    {
        name: "yolov5"
        kind: KIND_GPU
        count: 1
        gpus: [0,1,2,3,4,5,6,7]
    }
]
